server:
  port: ${PORT:8000}
spring:
  datasource:
    url: jdbc:postgres://HdmIPdYhvrDvTHhKNr038M9sk5WDjUyT@dpg-cks4l97d47qs73ads5j0-a:5432/osmsdb
    username: root
    password: HdmIPdYhvrDvTHhKNr038M9sk5WDjUyT

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
